Name-based sockets - daemon: NameStackDaemon.cpp File Reference
NameStackDaemon.cpp File Reference
#include <stdlib.h>
#include <jni.h>
#include "log.h"
#include "daemon.h"
Functions
void Java_com_ericsson_namestackd_daemon_Run (JNIEnv *env, jobject obj)
static int jniRegisterNativeMethods (JNIEnv *env, const char *className, const JNINativeMethod *gMethods, int numMethods)
JNIEXPORT jint JNI_OnLoad (JavaVM *vm, void *reserved)
Variables
static JNINativeMethod sMethods []
Function Documentation
void Java_com_ericsson_namestackd_daemon_Run (JNIEnv * env, jobject obj)
Definition at line 7 of file NameStackDaemon.cpp.
References run_daemon().
{
    run_daemon();
}
JNIEXPORT jint JNI_OnLoad (JavaVM * vm, void * reserved)
Definition at line 35 of file NameStackDaemon.cpp.
References jniRegisterNativeMethods(), and sMethods.
{
    JNIEnv* env = NULL;
    if (vm->GetEnv((void**)&env, JNI_VERSION_1_4) != JNI_OK)
        return -1;
    jniRegisterNativeMethods(env, "com/ericsson/namestackd/daemon",
                             sMethods, sizeof(sMethods) / sizeof(sMethods[0]));
    return JNI_VERSION_1_4;
}
static int jniRegisterNativeMethods (JNIEnv * env, const char * className, const JNINativeMethod * gMethods, int numMethods) [static]
Definition at line 12 of file NameStackDaemon.cpp.
References LOGE, and LOGV.
Referenced by JNI_OnLoad().
{
    jclass clazz;
    LOGV("Registering %s natives\n", className);
    clazz = env->FindClass(className);
    if (clazz == NULL) {
        LOGE("Native registration unable to find class '%s'\n", className);
        return -1;
    }
    if (env->RegisterNatives(clazz, gMethods, numMethods) < 0) {
        LOGE("RegisterNatives failed for '%s'\n", className);
        return -1;
    }
    return 0;
}
Variable Documentation
JNINativeMethod sMethods[] [static]
Initial value:
 {
    { "Run", "()V", (void*)Java_com_ericsson_namestackd_daemon_Run },
}
Definition at line 30 of file NameStackDaemon.cpp.
Referenced by JNI_OnLoad().