Name-based sockets - daemon: daemon.h File Reference
daemon.h File Reference
Functions
int run_daemon (void)
Function Documentation
int run_daemon (void)
Definition at line 695 of file daemon.c.
References do_delete_registration(), do_qualify(), do_query(), do_register(), LOGE, LOGI, LOGW, MAX_PAYLOAD, NAME_STACK_NAME_QUERY, NAME_STACK_QUALIFY_QUERY, NAME_STACK_REGISTER, NAME_STACK_REGISTER_DELETE, NAME_STACK_REGISTER_QUERY, and sock_fd.
Referenced by Java_com_ericsson_namestackd_daemon_Run(), and main().
{
        res_init();
        sock_fd = socket(PF_NETLINK, SOCK_DGRAM, NETLINK_NAME_ORIENTED_STACK);
        if (sock_fd >= 0) {
                struct sockaddr_nl src_addr, dest_addr;
                struct nlmsghdr *nlh = NULL;
                struct iovec iov;
                struct msghdr msg;
                struct pollfd pfd;
                memset(&src_addr, 0, sizeof(src_addr));
                src_addr.nl_family = AF_NETLINK;
                bind(sock_fd, (struct sockaddr*)&src_addr, sizeof(src_addr));
                memset(&dest_addr, 0, sizeof(dest_addr));
                dest_addr.nl_family = AF_NETLINK;
                nlh = malloc(NLMSG_SPACE(MAX_PAYLOAD));
                /* Send a register message
                 * FIXME: the message is empty, do I really need MAX_PAYLOAD
                 * data bytes?
                 */
                nlh->nlmsg_len = NLMSG_SPACE(MAX_PAYLOAD);
                nlh->nlmsg_type = NAME_STACK_REGISTER;
                nlh->nlmsg_pid = 0;
                nlh->nlmsg_flags = 0;
                *(char *)NLMSG_DATA(nlh) = 0;
                iov.iov_base = (void *)nlh;
                iov.iov_len = nlh->nlmsg_len;
                msg.msg_name = (void *)&dest_addr;
                msg.msg_namelen = sizeof(dest_addr);
                msg.msg_iov = &iov;
                msg.msg_iovlen = 1;
                sendmsg(sock_fd, &msg, 0);
                /* Read message from kernel */
                memset(nlh, 0, NLMSG_SPACE(MAX_PAYLOAD));
                recvmsg(sock_fd, &msg, 0);
                /* FIXME: check that it's a reply */
                LOGI("%s", "Received registration reply\n");
                memset(nlh, 0, NLMSG_SPACE(MAX_PAYLOAD));
                pfd.fd = sock_fd;
                pfd.events = POLLIN;
                while (poll(&pfd, 1, -1)) {
                        recvmsg(sock_fd, &msg, 0);
                        switch (nlh->nlmsg_type)
{
                        case NAME_STACK_NAME_QUERY:
                                do_query(nlh->nlmsg_seq,
                                         NLMSG_DATA(nlh),
                                         NLMSG_PAYLOAD(nlh, 0));
                                break;
                        case NAME_STACK_QUALIFY_QUERY:
                                do_qualify(nlh->nlmsg_seq,
                                           NLMSG_DATA(nlh),
                                           NLMSG_PAYLOAD(nlh, 0));
                                break;
                        case NAME_STACK_REGISTER_QUERY:
                                do_register(nlh->nlmsg_seq,
                                            NLMSG_DATA(nlh),
                                            NLMSG_PAYLOAD(nlh, 0));
                                break;
                        case NAME_STACK_REGISTER_DELETE:
                                do_delete_registration(nlh->nlmsg_seq,
                                                       NLMSG_DATA(nlh),
                                                       NLMSG_PAYLOAD(nlh, 0));
                                break;
                        default:
                                LOGW("unhandled msg type %d\n",
                                     nlh->nlmsg_type);
                        }
                        memset(nlh, 0, NLMSG_SPACE(MAX_PAYLOAD));
                }
                /* Close Netlink Socket */
                close(sock_fd);
        }
        else
                LOGE("socket failed: %s (%d)\n", strerror(errno), errno);
        return 0;
}